// layout.js or _app.js or RootLayout.js

export const metadata = {
  title: "Violet's App",
  description: 'Generated by Next.js',
  // Specify the path to the manifest and the favicon
  icons: {
    icon: '/favicon192.ico', // 192x192 is commonly used for the home screen icon
    apple: '/favicon192.ico', // For Apple devices (optional)
    // You can add other sizes for different platforms
  },
  themeColor: '#ffffff',  // This can be the background color of the app when installed
}

import './globals.css'; // Import your global styles

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
 
      </head>
      <body>{children}</body>
    </html>
  )
}
