// layout.js or _app.js or RootLayout.js

export const metadata = {
  title: "Violet's App",
  description: 'Generated by Next.js',
  // Specify the path to the manifest and the favicon
 
  themeColor: '#ffffff',  // This can be the background color of the app when installed
}

import './globals.css'; // Import your global styles

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
 
      </head>
      <body>{children}</body>
    </html>
  )
}
